export const IpcChannel = {
  settingsGet: 'settings.get',
  settingsSet: 'settings.set',
  providerList: 'provider.list',
  providerCreate: 'provider.create',
  providerUpdate: 'provider.update',
  providerDelete: 'provider.delete',
  agentList: 'agent.list',
  agentCreate: 'agent.create',
  agentUpdate: 'agent.update',
  agentDelete: 'agent.delete',
  agentVersions: 'agents.versions',
  agentRollback: 'agents.rollback',
  taskCreate: 'task.create',
  taskCancel: 'task.cancel',
  taskPause: 'task.pause',
  taskResume: 'task.resume',
  taskRollback: 'task.rollback',
  taskRetry: 'task.retry',
  approvalResolve: 'approval.resolve',
  chatSend: 'chat.send',
  chatListSessions: 'chat.listSessions',
  chatCreateSession: 'chat.createSession',
  chatLoadMessages: 'chat.loadMessages',
  squadStart: 'squad.start',
  squadCurrent: 'squad.current',
  daemonStatus: 'daemon.status',
  daemonRestart: 'daemon.restart',
  secretsSet: 'secrets.set',
  secretsGet: 'secrets.get',
  secretsDelete: 'secrets.delete',
  dialogOpenFile: 'dialog.openFile',
  diagnosticsRun: 'diagnostics.run',
  envInfo: 'diagnostics.env',
  workspaceTree: 'workspace.tree',
  workspaceRead: 'workspace.read',
  indexReindex: 'index.reindex',
  diffApplyAll: 'diff.applyAll',
  diffRead: 'diff.read',
  taskboardList: 'taskboard.list',
} as const;

export const IpcEvent = {
  chatDelta: 'chat:delta',
  chatDone: 'chat:done',
  taskLog: 'task:log',
  taskState: 'task:state',
  taskComplete: 'task:complete',
  taskFailed: 'task:failed',
  squadStatus: 'squad:status',
  squadEvent: 'squad:event',
  toastPush: 'toast:push',
  approvalRequest: 'approval:request',
} as const;
