import { IpcChannel, IpcEvent } from './ipc-channels';

/** Renderer may invoke only these IPC channels (preload gate). */
export const ALLOWED_INVOKE = new Set<string>([
  IpcChannel.settingsGet,
  IpcChannel.settingsSet,
  IpcChannel.providerList,
  IpcChannel.providerCreate,
  IpcChannel.providerUpdate,
  IpcChannel.providerDelete,
  IpcChannel.agentList,
  IpcChannel.agentCreate,
  IpcChannel.agentUpdate,
  IpcChannel.agentDelete,
  IpcChannel.agentVersions,
  IpcChannel.agentRollback,
  IpcChannel.taskCreate,
  IpcChannel.taskCancel,
  IpcChannel.taskPause,
  IpcChannel.taskResume,
  IpcChannel.taskRollback,
  IpcChannel.taskRetry,
  IpcChannel.approvalResolve,
  IpcChannel.chatSend,
  IpcChannel.chatListSessions,
  IpcChannel.chatCreateSession,
  IpcChannel.chatLoadMessages,
  IpcChannel.chatDeleteSession,
  IpcChannel.chatRenameSession,
  IpcChannel.squadStart,
  IpcChannel.squadCurrent,
  IpcChannel.daemonStatus,
  IpcChannel.daemonRestart,
  'dialog.pickPath',
  IpcChannel.diagnosticsRun,
  IpcChannel.envInfo,
  IpcChannel.windowGetChrome,
  IpcChannel.taskboardList,
  'shortcuts.get',
  'shortcuts.set',
  'agent-templates.list',
  'agent-templates.createAgent',
  'mcp.list',
  'mcp.create',
  'mcp.delete',
  'mcp.test',
  'skills.list',
  'skills.importLocal',
  'skills.importUrl',
  'skills.delete',
  'workspace.bind',
  'workspace.listBound',
  'workspace.loadContext',
  'workspace.copyFiles',
  'workspace.tree',
  'workspace.read',
  'index.reindex',
  'index.search',
  'mention.search',
  'diff.applyAll',
  'diff.read',
  'dialog.saveText',
  'config.readPickedFile',
  'provider.listModels',
  'provider.listSelectableModels',
  'provider.addModel',
  'provider.deleteModel',
  'provider.setEnabled',
  'provider.setModelEnabled',
  'provider.test',
  'usage.summary',
  'usage.list',
  'audit.list',
  'audit.export',
  'logs.list',
  'logs.read',
  'artifacts.list',
  'artifacts.save',
  'backup.list',
  'backup.create',
  'backup.restore',
  'app.relaunch',
  'wipe.run',
  'squad.create',
  'squad.graph',
  'squad.approve',
  'workflow.run',
  'proxy.get',
  'proxy.set',
  'config.export',
  'config.import',
  'export.session',
  'templates.list',
  'templates.create',
  'templates.update',
  'templates.delete',
  'templates.render',
  'search.global',
  'search.providers.get',
  'search.providers.set',
  'runtime.status',
  'runtime.conflicts',
  'runtime.resolveConflict',
  'daemon.injectionApprovals.list',
  'daemon.injectionApprovals.approve',
  'office.selection',
  'office.writing',
  'office.writing.translate',
  'office.pdf.extract',
  'office.pdf.summarize',
  'office.webview.open',
  'office.webview.summarize',
  'office.video.summarize',
  'office.image.generate',
  'office.file.analyze',
]);

/** Renderer may subscribe only to these main→renderer events. */
export const ALLOWED_EVENTS = new Set<string>([
  IpcEvent.chatDelta,
  IpcEvent.chatDone,
  IpcEvent.taskLog,
  IpcEvent.taskState,
  IpcEvent.taskComplete,
  IpcEvent.taskFailed,
  IpcEvent.squadStatus,
  IpcEvent.squadEvent,
  IpcEvent.toastPush,
  IpcEvent.approvalRequest,
  IpcEvent.windowChrome,
]);

export function assertAllowedInvoke(channel: string): void {
  if (!ALLOWED_INVOKE.has(channel)) {
    throw new Error(`ipc invoke not allowed: ${channel}`);
  }
}

export function assertAllowedEvent(channel: string): void {
  if (!ALLOWED_EVENTS.has(channel)) {
    throw new Error(`ipc event not allowed: ${channel}`);
  }
}
